modLoader="javafml"
loaderVersion="[0,)"
issueTrackerURL="https://github.com/TehNut/Hwyla/issues"
displayURL="https://github.com/TehNut/Hwyla"
authors="TehNut, ProfMobius"
[[mods]]
    modId="waila"
    version="${version}"
    displayName="Waila"
    description='''
    You are using Hwyla, a fork of Waila. You can find more information on the Hwyla CurseForge page.

    Hwyla (Here's What You're Looking At) is a UI improvement mod aimed at providing block information directly in-game.
    '''
[[dependencies.waila]]
    modId="forge"
    mandatory=true
    versionRange="[15.24.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waila]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.14)"
    ordering="NONE"
    side="BOTH"